//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalStatusCallCleared : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalStatusCallCleared(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalStatusCallCleared obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalStatusCallCleared() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalStatusCallCleared(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalStatusCallCleared_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusCallCleared_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public string reason {
    set {
      OPALPINVOKE.OpalStatusCallCleared_reason_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusCallCleared_reason_get(swigCPtr);
      return ret;
    } 
  }

  public string statistics {
    set {
      OPALPINVOKE.OpalStatusCallCleared_statistics_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusCallCleared_statistics_get(swigCPtr);
      return ret;
    } 
  }

  public OpalStatusCallCleared() : this(OPALPINVOKE.new_OpalStatusCallCleared(), true) {
  }

}
