//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum OpalUserInputModes {
  OpalUserInputDefault,
  OpalUserInputAsQ931,
  OpalUserInputAsString,
  OpalUserInputAsTone,
  OpalUserInputAsRFC2833,
  OpalUserInputInBand
}
