/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OPAL implements OPALConstants {
  public static SWIGTYPE_p_OpalHandleStruct OpalInitialise(long[] INOUT, String INPUT) {
    long cPtr = OPALJNI.OpalInitialise(INOUT, INPUT);
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpalHandleStruct(cPtr, false);
  }

  public static void OpalShutDown(SWIGTYPE_p_OpalHandleStruct IN) {
    OPALJNI.OpalShutDown(SWIGTYPE_p_OpalHandleStruct.getCPtr(IN));
  }

  public static OpalMessage OpalGetMessage(SWIGTYPE_p_OpalHandleStruct arg0, long arg1) {
    long cPtr = OPALJNI.OpalGetMessage(SWIGTYPE_p_OpalHandleStruct.getCPtr(arg0), arg1);
    return (cPtr == 0) ? null : new OpalMessage(cPtr, false);
  }

  public static OpalMessage OpalSendMessage(SWIGTYPE_p_OpalHandleStruct arg0, OpalMessage arg1) {
    long cPtr = OPALJNI.OpalSendMessage(SWIGTYPE_p_OpalHandleStruct.getCPtr(arg0), OpalMessage.getCPtr(arg1), arg1);
    return (cPtr == 0) ? null : new OpalMessage(cPtr, false);
  }

  public static void OpalFreeMessage(OpalMessage IN) {
    OPALJNI.OpalFreeMessage(OpalMessage.getCPtr(IN), IN);
  }

}
